project: "climates"

model: {
  id: "mlp",
  type: "MLPClassifier",
  grid_parm: [{'activation':['logistic', 'tanh', 'relu'],
    'hidden_layer_sizes':[[256,128,64], [512,256,128,64],[1024,512,256,128,64]],
    'learning_rate':['constant', 'invscaling'],
    'learning_rate_init':[0.005, 0.0001, 0.0005],
  }],
  search_args: {
    cv: 3, # k fold cross validation. 
    scoring: 'f1_macro',
    verbose: 3,
    n_jobs: -1, # -1이면 search할때 CPU코어 전부 다쓰는거에요. 
  },
  args: {
    activation: "relu",
    hidden_layer_sizes: [
      512, 256, 128, 64,
    ],
    learning_rate: 'invscaling',
    learning_rate_init: 0.005,
  },
}

data: {
  train_path: "../datasets/train.csv",
  test_path: "../datasets/test.csv",
  processed_train_path: "../datasets/word_cnt_baseline_train",
  processed_test_path: "../datasets/word_cnt_baseline_test",
  sample_path: '../datasets/sample_submission.csv',
  submission_path: '../saved/mlp_submission.csv',
}
