project: "Samsung AI Challenge for Scientific Discovery"

model: {
  id: "ChemBERTa_decoder(mlp(sdf_features + pfp_features)+resnet50(image), seq)",
  pad_token_id: 1,
}

train: {
  lr: 5e-5,
  weight_decay: 1e-2,
  train_batch_size: 40,
  dev_batch_size: 40,
  test_batch_size: 40,
  save_path: '../saved',
  num_workers: 40,
  args: {
    gpus: 1,
    precision: 16,
    accumulate_grad_batches: 1,
    val_check_interval: 1.0,
    gradient_clip_val: 1.0,
    max_steps: 10000,
  }
}

data: {
  max_seq_length: 200,
  radius: 1,
  n_sdf_features: 16,
  n_pfp_features: 2048,
  n_mordred_features: 1461,
  train_test_split: 0.01,
  cache_file_name: '../datasets/datasets.pkl',
  train_path: "../datasets/train.csv",
  dev_path: "../datasets/dev.csv",
  test_path: "../datasets/test.csv",
  sample_submission_path: "../datasets/sample_submission.csv",
  submission_path: "../result/SMILES_hybrid_submission.csv",
}
